#!/usr/bin/env bash
PIPEWIRE_USER=$(ps -o user= -p `pidof pipewire`)

if [[ -n $PIPEWIRE_USER && -n $ACTION ]]; then
    if [ $ACTION == "add" ]; then
        systemctl --machine=${PIPEWIRE_USER}@.host --user start fiio-k3-fix.service
    else
        systemctl --machine=${PIPEWIRE_USER}@.host --user stop fiio-k3-fix.service
    fi
fi
